### PR TITLE
Upgrade Vue to v2.0.0

### PR DESCRIPTION
**Pull request by yamgent**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [X] Other, please explain: Migration works

Follows MarkBind/markbind#245

**What is the rationale for this request?**
Migration to Vue 2.0 as part of the major migration to bootstrap-vue.

**What changes did you make? (Give an overview)**
Ensure that all components are actually compileable on Vue 2.0.

**Provide some example code that this change will affect:**
NIL

**Is there anything you'd like reviewers to focus on?**
NIL

**Testing instructions:**
1. `npm install` to update Vue to v2 (when you are off this branch, remember to downgrade back to v1).
2. `npm run build`
3. Copy `dist/vue-strap.min.js` to your MarkBind repository (`assets/js`).
4. Copy `node_modules/vue/dist/vue.min.js` to your MarkBind repository (`assets/js`) to upgrade to Vue 2.0.
5. Create a new MarkBind website (`markbind init`).
6. Try a component that works without additional migration efforts (i.e. `TipBox`, `pic`)*. For example:
```html
<tip-box type="wrong">
    wrong
</tip-box>

<pic src="https://vuejs.org/images/logo.png" alt="Logo">
    Logo For Vue.js
</pic>
```
7. `markbind serve` and check that it still works for these components (otherwise ensure that you did step 4).

 *These two will not cause any additional errors after upgrading to vue 2.0, and so they work. The rest of the components are not migrated yet, they only have their compilation errors fixed but they still use some outdated attributes and features, so they will have runtime errors.

### CODE REVIEW

**Comment by yamgent** [comment]
After this PR, we will be using Vue 2.0, and compilation errors inside the components are fixed.

However, no compilation errors != no runtime errors. We are still not compatible with Vue 2.0 yet. Most of the components are using outdated Vue syntax, and thus will not work when trying to use them (except for `TipBox` and `pic`, these are quite simple components, so they will still work in Vue 2.0).

The documentation is also blank atm for the same reasons.

According to the migration helper, there are still around ~300 errors to fix inside these components before we are completely compatible with Vue 2.0. These should be fixed in subsequent PRs (I attached the error list [here](https://gist.github.com/yamgent/ef6d1c580334c2d1f343b3e3a914c140). Btw these are from the [migration helper](https://github.com/vuejs/vue-migration-helper), not the actual compiler, so we should be prepared to anticipate more errors and bugs).

**Comment by yamgent** [comment]
PR ready for review.

**Comment by acjh** [comment]
Let's go ahead with this.

**Comment by yamgent** [comment]
I recently added a new fix to the migration branch, to sort out a porting error caused by this PR regarding dangling `v-else` attributes (the commit is https://github.com/MarkBind/vue-strap/commit/98864777b3d1933b4c921992963c2d5b8863d287). Details of the porting error can be found in the commit message.
